name: testbot
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  run:
    name: Add a text file
    runs-on: ubuntu-latest

    steps:
      # If you need to, you can check out your repo to a different location
      - uses: actions/checkout@v2
        with:
          path: './'

      # You can make whatever type of change to the repo...
      - run: echo "123" > ./.config

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Add the very useful text file'
          add: '.config --force'
          cwd: './'




