name: testbot

-name: Clone this repo.
   run:
    git clone https://github.com/keeptpa/Openwrt
    cd Openwrt/
    rm .config
    touch .config
    echo this means succeed >> .config

- name: push .config file.
      uses: EndBug/add-and-commit@v7.4.0
      with:
        add: '.config'
        author_name: ConfigMaker
        message: 'Updated By Bot'
