name: testbot
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: Clone this repo
      run: |
         git clone https://github.com/keeptpa/Openwrt
         cd ./Openwrt/
         rm .config
         touch .config
         echo this means succeed >> .config
         
    - name: push
      uses: EndBug/add-and-commit@v7.4.0
      with:
         add: '.config'
         author_name: ConfigMaker
         cwd: './'
         message: 'Updated By Bot'



